"""change_text_to_json_columns

Revision ID: 7d67ed3acc62
Revises: 7110b2bfcb63
Create Date: 2025-07-13 21:20:04.562225

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d67ed3acc62"
down_revision: Union[str, Sequence[str], None] = "7110b2bfcb63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use explicit casting for TEXT to JSON conversion
    op.execute("ALTER TABLE user_profiles ALTER COLUMN clusters TYPE JSON USING clusters::json")
    op.execute("ALTER TABLE user_profiles ALTER COLUMN movies TYPE JSON USING movies::json")
    op.create_index(op.f("ix_user_profiles_user_id"), "user_profiles", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_profiles_user_id"), table_name="user_profiles")
    op.alter_column("user_profiles", "movies", existing_type=sa.JSON(), type_=sa.TEXT(), existing_nullable=True)
    op.alter_column("user_profiles", "clusters", existing_type=sa.JSON(), type_=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
